# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# Directory coloring found here: http://www.macosxhints.com/article.php?story=20031027145026892
export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagacad
export HISTCONTROL=erasedups

# Get MacVim to load before system vim:
#export /Applications/MacVim.app/Contents/MacOS:$PATH
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/local/tmux/bin
export PATH=$PATH:$HOME/local/cmake/bin
export PATH=$PATH:$HOME/src/rkt-v0.6.1

# Add Python PIP bin to beginning of PATH
if [ -d "$HOME/.local/bin" ]; then
  PATH=$HOME/.local/bin:$PATH
fi

# Don't call shopt from zsh
if [ $SHELL = '/bin/bash' ]; then
  # append to the history file, don't overwrite it
  shopt -s histappend

  # check the window size after each command and, if necessary,
  # update the values of LINES and COLUMNS.
  shopt -s checkwinsize

  # If set, the pattern "**" used in a pathname expansion context will
  # match all files and zero or more directories and subdirectories.
  #shopt -s globstar
fi

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi


# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
        export TERM=xterm-256color
    else
	color_prompt=
    fi
fi

unset color_prompt force_color_prompt

# Some more ls aliases
alias ll='ls -alF'
alias la="ls -la"
alias grep="grep --color=auto --line-number --exclude='*.min.js' --exclude='*third_party/*' --exclude='*\.git*' --exclude='*\.bin*' --exclude='*server/static/js*'"
#alias grep="grep --color=auto --line-number --exclude='*.min.js' --exclude='*third_party/*' --exclude='*\.git*' -exclude='*node_modules*' --exclude='*\.bin*' --exclude='*server/static/js*'"
alias tmuxr="(tmux ls | grep -vq attached && tmux at) || tmux"
alias sudo='sudo env PATH=$PATH'
alias xclip='xclip -selection c'


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

export FLEETCTL_ENDPOINT=http://172.17.8.101:4001
export KUBERNETES_MASTER=http://172.17.8.101:8080
