# Pat to your oh-my-zsh installation.
export ZSH="/home/lukebayes/.oh-my-zsh"

# Change if terminal color scheme changes... 
SOLARIZED_THEME=dark

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Ensure history is preserved
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(ssh-agent git)
plugins=(ssh-agent)

source $ZSH/oh-my-zsh.sh

# Add Github key to ssh-agent
ssh-add $HOME/.ssh/github_rsa

# User configuration
# export JAVA_CLASSPATH="$HOME/javalib/clojure-1.8.0"

export PATH="$HOME/bin:$PATH"
export PATH="$PATH:$HOME/src/eagle-9.6.2"
export PATH="$PATH:$HOME/src/zig"
export PATH="$PATH:/bin"
export PATH="$PATH:/sbin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/usr/local/cuda-11.4/bin"
export PATH="$HOME/.local/bin:$PATH"

# Add cuda to the LD Library Path
export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=:$LD_LIBRARY_PATH:"/usr/local/cuda-11.4/lib64"

# Unused or invalid paths
# export PATH="$PATH:/Users/lukebayes/bin"
# export PATH="$PATH:/Volumes/Deep Storage 01/SDK/platform-tools"
# export PATH="$PATH:/Applications/Racket v6.12/bin"
# export PATH="$PATH:$HOME/.npm-global/bin"
# export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/2.7/bin"
# export PATH="$PATH:$HOME/local/cmake/bin"
# export PATH="$PATH:/opt/X11/bin"
# export PATH="$PATH:/usr/local/go/bin"

# Google build tools
# export PATH="$HOME/depot_tools:$PATH"
# YouTube Cobalt clang and build tools
# export PATH="$HOME/Projects/foss/cobalt/src/third_party/llvm-build/Release+Asserts/bin:$PATH"
# Nodejs
# export PATH="$HOME/Projects/foss/node/node-v12.18.2-linux-x64/bin:$PATH"
# JetBrains DataGrip
# export PATH="$PATH:/home/lukebayes/src/DataGrip-2021.2.1/bin"

export PICO_SDK_PATH=/home/lukebayes/Projects/foss/raspberrpi/pico-sdk

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
# alias make="make -j 12"
alias zb="zig build"
alias make="make -j 12"
# alias vim="nvim"

# Turn OFF the muthereffing System Bell
xset b off
xset b 0 0 0

