FROM ubuntu:14.04

ENV BUILD_PACKAGES build-essential \
  cmake \
  git \
  libsqlite3-dev \
  libxml2-dev \
  libxslt1-dev \
  nodejs \
  ruby \
  ruby-dev \
  tmux \
  vim \
  zip \
  zlib1g-dev

# Install Ruby and Rails dependencies
RUN apt-get update && apt-get install -qfy $BUILD_PACKAGES && \
  apt-get remove -y $BUILD_PACKAGES && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

